# Generated by Django 2.1.7 on 2019-04-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='needforvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(blank=True, upload_to='')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
