# Generated by Django 2.1.7 on 2019-04-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_needforvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField(verbose_name=500)),
            ],
        ),
    ]
