# Generated by Django 2.1.7 on 2019-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(),
        ),
    ]
